matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.502
      solution: chineseDuck.sln
      script:
        - dotnet restore
    - node_js: "10"
      install:
        - npm install
      script:
        - npm run test
