language: csharp
dotnet: 2.1.502
mono: none
solution: chineseDuck.sln
install:
  - npm install
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./src/bot/chineseDuck.Bot.UnitTests/chineseDuck.Bot.UnitTests.csproj -c Release -f netcoreapp2.1
  - npm run test
