language: csharp
dotnet: 2.1.502
solution: chineseDuck.sln
before_install:
  - sudo apt-get install libcurl3
install:
  - npm install
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./src/bot/chineseDuck.Bot.UnitTests/chineseDuck.Bot.UnitTests.csproj -c Release -f netcoreapp2.1
  - npm run test
