matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.502
      solution: chineseDuck.sln
      script:
        - dotnet restore
        - dotnet build
        - dotnet test ./src/bot/chineseDuck.Bot.UnitTests/chineseDuck.Bot.UnitTests.csproj -c Release -f netcoreapp2.1
    - node_js: "10"
      install:
        - npm install
      script:
        - npm run test
