version: '3.5'
services:
  mongoDb:
    image: mongo:latest
    hostname: mongoDb
    restart: unless-stopped
    container_name: mongoDb

    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pwd

    volumes:
      - ./config/db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    networks:
      udd3r_net:
          ipv4_address: 10.1.1.4
  websrv:
    image: umputun/nginx-le:latest
    hostname: websrv
    restart: unless-stopped
    container_name: websrv

    volumes:
      - ./config/websrv.conf:/etc/nginx/service.conf
      #- ./etc/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"

    environment:
        - TZ=Europe
        - LETSENCRYPT=true
        - LE_EMAIL=CERT_EMAIL
        - LE_FQDN=PUBLIC_URL
        #- SSL_CERT=le-crt.pem
        #- SSL_KEY=le-key.pem
        #- SSL_CHAIN_CERT=le-chain-crt.pem
        #- NGINX_VERSION=1.15.7-1~stretch
        #- NJS_VERSION=1.15.7.0.2.6-1~stretch
    
    networks:
      udd3r_net:
        ipv4_address: 10.1.1.5
  webApi:
    image: node:10
    hostname: webApi
    working_dir: /app
    restart: unless-stopped
    container_name: webApi
    command: bash -c "npm install && node /app/server.js"
    networks:
      udd3r_net:
          ipv4_address: 10.1.1.6
    volumes:
      - ./package.json:/app/package.json
      - ./build:/app
      - ./build/public:/app/public
    ports:
      - "3000:3000"
  bot:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    working_dir: /app
    hostname: bot
    restart: unless-stopped
    container_name: bot
    command: bash -c "dotnet /app/chineseDuck.BotService.dll"
    volumes:
      - ./src/bot/chineseDuck.BotService/bin/release/netcoreapp2.1/publish:/app
    ports:
      - "8080:8080"
    networks:
      udd3r_net:
          ipv4_address: 10.1.1.7

networks:
  udd3r_net:
    name: udd3r
    ipam:
      config:
        - subnet: 10.1.1.0/24