version: '3.5'
services:
  websrv:
    image: umputun/nginx-le:latest
    hostname: websrv
    restart: unless-stopped
    container_name: websrv

    volumes:
      - ./config/websrv.conf:/etc/nginx/service.conf
      #- ./etc/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"

    environment:
        - TZ=Europe
        - LETSENCRYPT=true
        - LE_EMAIL=north@live.ru
        - LE_FQDN=chinese-duck.com
        - TELEGRAM_BOT_KEY=000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        #- SSL_CERT=le-crt.pem
        #- SSL_KEY=le-key.pem
        #- SSL_CHAIN_CERT=le-chain-crt.pem
        #- NGINX_VERSION=1.15.7-1~stretch
        #- NJS_VERSION=1.15.7.0.2.6-1~stretch
    
    networks:
      udd3r_net:
        ipv4_address: 10.1.1.5
  mongoDb:
    image: mongo:latest
    hostname: mongoDb
    restart: unless-stopped
    container_name: mongoDb

    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pwd

    volumes:
      - ./config/db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    networks:
      udd3r_net:
          ipv4_address: 10.1.1.4
networks:
  udd3r_net:
    name: udd3r
    ipam:
      config:
        - subnet: 10.1.1.0/24