/* 
 * Chinese Duck Bot Api
 *
 * Chinese Duck Bot Api
 *
 * OpenAPI spec version: 1.1.1-oas3
 * Contact: north@live.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Runtime.Serialization;
using ChineseDuck.Bot.Interfaces.Data;
using Newtonsoft.Json;

namespace ChineseDuck.Bot.Rest.Model
{
    /// <summary>
    /// WordFileBytes
    /// </summary>
    [DataContract]
    public class WordFileBytes : BaseModel, IWordFileBytes
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "_id", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "_id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Bytes
        /// </summary>
        [DataMember(Name="bytes", EmitDefaultValue=false)]
        public byte[] Bytes { get; set; }
    }

}
